name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        . venv/bin/activate
        flake8 src tests

    - name: Run unit tests
      run: |
        . venv/bin/activate
        python -m unittest discover -s tests
